# Generated by Django 4.1.4 on 2023-12-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='administrator_login',
            fields=[
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('admin_id', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='administrator_login/')),
                ('email_id', models.EmailField(blank=True, max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('reenter_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='administrator_questions',
            fields=[
                ('question', models.CharField(default=None, max_length=500, primary_key=True, serialize=False)),
                ('option_A', models.CharField(max_length=100)),
                ('option_B', models.CharField(max_length=100)),
                ('option_C', models.CharField(max_length=100)),
                ('option_D', models.CharField(max_length=100)),
                ('correct_answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='administrator_signin',
            fields=[
                ('email_id', models.EmailField(blank=True, max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
