# Generated by Django 4.1.4 on 2023-12-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator_questions',
            name='id',
            field=models.IntegerField(default=None, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='administrator_questions',
            name='question',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
