# Generated by Django 4.1.4 on 2023-12-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_quiz', '0002_administrator_questions_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator_questions',
            name='id',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
    ]
