# Generated by Django 4.1.4 on 2023-11-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_students_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='bio',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='students',
            name='chem',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='students',
            name='maths',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='students',
            name='phy',
            field=models.IntegerField(default=90),
        ),
    ]
