# Generated by Django 4.1.4 on 2023-11-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_students_bio_students_chem_students_maths_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='pcb',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='students',
            name='pcm',
            field=models.IntegerField(default=90),
        ),
    ]
